### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by SHAREN** [bcserv/downloadtable_statistics#1]
//SourceMod Batch Compiler
// by the SourceMod Dev Team

//// downloadtable_statistics.sp
//
// D:\CSGOServer\war3\1\csgo\addons\sourcemod\scripting\downloadtable_statistics.sp(279) : error 001: expected token: "-identifier-", but found ")"
//
// 1 Error.
//
// Compilation Time: 0,78 sec
// ----------------------------------------

Press enter to exit ...

**Comment by berni2288** [comment]
Hi, try with the Sourcemod 1.6 compiler.
